services:
  - type: web
    name: dropbox-index
    env: node
    plan: free
    buildCommand: yarn; yarn build
    startCommand: yarn start
    envVars:
      - key: DROPBOX_TOKEN
        value: 'C17II9MZfRYAAAAAAAAAAeYArLJIlYRjPa68uxttN6nD4Baua-xC2qw9qjWhud-q'
      - key: NEXT_PUBLIC_TITLE
        value: Luffy
