services:
  - type: web
    name: dropbox-index
    env: node
    plan: free
    buildCommand: yarn; yarn build
    startCommand: yarn start
    envVars:
      - key: DROPBOX_TOKEN
        value: 'asd'
      - key: NEXT_PUBLIC_TITLE
        value: Luffy
